---
language: python
python: "2.7"

services:
  - docker

before_install:
  - docker --version
  - docker info
  - export GALAXY_TRAVIS_USER=galaxy
  - export GALAXY_UID=1450
  - export GALAXY_GID=1450
  - export GALAXY_HOME=/home/galaxy
  - export GALAXY_USER=admin@galaxy.org
  - export GALAXY_USER_EMAIL=admin@galaxy.org
  - export GALAXY_USER_PASSWD=admin
  - export BIOBLEND_GALAXY_API_KEY=admin
  - export BIOBLEND_GALAXY_URL=http://localhost:8080

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - printf '[defaults]\nroles_path = ../' > ansible.cfg

  # download the Galaxy Docker image and build it to test the playrole
  - mkdir $HOME/galaxy-docker
  - wget -q -O - https://github.com/bgruening/docker-galaxy-stable/archive/master.tar.gz | tar xzf - --strip-components=1 -C $HOME/galaxy-docker
  # remove the submodule role
  - rm $HOME/galaxy-docker/galaxy/roles/galaxyprojectdotorg.galaxyextras/* -rf
  - sudo mkdir $GALAXY_HOME
  - cd $GALAXY_HOME
  - sudo su $GALAXY_TRAVIS_USER -c 'wget https://github.com/bgruening/bioblend/archive/master.tar.gz'
  - sudo su $GALAXY_TRAVIS_USER -c 'tar xfz master.tar.gz'
  - cd $GALAXY_HOME/bioblend-master
  - sudo su $GALAXY_TRAVIS_USER -c 'pip install --user --upgrade "tox>=1.8.0" "pep8<=1.6.2" '
  - sudo su $GALAXY_TRAVIS_USER -c 'python setup.py install --user'
  # remove flake8 testing for bioblend from tox
  - sudo su $GALAXY_TRAVIS_USER -c 'sed -i.bak "s/commands.*$/commands =/" tox.ini'

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i "localhost," tests/syntax.yml --syntax-check
  # Copy the ansible-playbook from this repo into the Docker roles directory and build the image.
  - cp -r ./* $HOME/galaxy-docker/galaxy/roles/galaxyprojectdotorg.galaxyextras/
  - ls -l $HOME/galaxy-docker/galaxy/roles/galaxyprojectdotorg.galaxyextras/
  - cd $HOME/galaxy-docker/galaxy && docker build -t galaxy-docker/test .
  - |
    docker run -d -p 8080:80 -p 8021:21 -p 8800:8800 \
    --name galaxy_test_container \
    --privileged=true \
    -e GALAXY_CONFIG_ALLOW_USER_DATASET_PURGE=True \
    -e GALAXY_CONFIG_ALLOW_LIBRARY_PATH_PASTE=True \
    -e GALAXY_CONFIG_ENABLE_USER_DELETION=True \
    -e GALAXY_CONFIG_ENABLE_BETA_WORKFLOW_MODULES=True \
    -v /tmp/:/tmp/ \
    galaxy-docker/test
  - sleep 10
  # Test FTP Server
  - curl --fail $BIOBLEND_GALAXY_URL/api/version
  - time > $HOME/time.txt && curl --fail -T $HOME/time.txt ftp://localhost:8021 --user $GALAXY_USER:$GALAXY_USER_PASSWD
  - curl --fail ftp://localhost:8021 --user $GALAXY_USER:$GALAXY_USER_PASSWD
  # Run bioblend nosetests with the same UID and GID as the galaxy user inside if Docker
  # this will guarantee that exchanged files bewteen bioblend and Docker are read & writable from both sides
  - sudo -E su $GALAXY_TRAVIS_USER -c "export PATH=$GALAXY_HOME/.local/bin/:$PATH && cd $GALAXY_HOME/bioblend-master && tox -e $TOX_ENV -- -e 'test_download_dataset'"
  # Test the 'new' tool installation script
  - docker run galaxy-docker/test bash -c "install-tools $GALAXY_HOME/ansible/galaxy-tools-playbook/files/tool_list.yaml"
